version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    groups:
      all-updates:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    groups:
      non-major-updates:
        update-types:
          - minor
          - patch
