allprojects {
  afterEvaluate {
    if (extensions.findByName("android") != null) {
      android.ndkVersion = System.getenv("NDK_VERSION")
      if (android.externalNativeBuild.cmake.path != null) {
        android.externalNativeBuild.cmake.version = System.getenv("CMAKE_VERSION")
      }
    }
  }
}
