const BIOME = "biome.json";
const RATCHET = ".size-limit.json";
const STRYKER = "stryker.config.json";
const CYCLOMATIC = ".oxlintrc.json";
const JOURNEY = "tests/e2e/journey.spec.ts";
const GESTURE = "tests/e2e/auditorium.spec.ts";
const DUPLICATION = ".jscpd.json";
const WORKFLOW = ".github/workflows/ci.yml";

export const GATE_CLAIMS = [
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*A class no stylesheet rules is refused by Biome's `noUndeclaredClasses`\*\*/,
    holds: "the class rule that gates the build",
    pattern: '"noUndeclaredClasses": "error"',
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /by Biome's \[`noExcessiveCognitiveComplexity`\]/,
    holds: "the complexity rule that gates the build",
    pattern: "noExcessiveCognitiveComplexity",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /The line counter is \[cloc\]/,
    holds: "the toolchain naming the counter this decision picked",
    pattern: "cloc",
    paths: [
      "package.json",
      ".github",
      "tools",
      ":!*.test.ts",
      ":!*.fixtures.ts",
    ],
    files: 2,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*The number and its exception process\.\*\*/,
    holds: "the cyclomatic limit that gates the build",
    pattern: '"max": 10',
    paths: [CYCLOMATIC],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /the same documented meaning of `classic`/,
    holds: "the counting variant the limit is defined over",
    pattern: '"variant": "classic"',
    paths: [CYCLOMATIC],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*Lines per file\*\* may not exceed 300, by Biome's/,
    holds: "the file length rule that gates the build",
    pattern: "noExcessiveLinesPerFile",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /calls it greater than or equal to a break threshold of 100, and exits/,
    holds: "the mutation gate's breaking threshold",
    pattern: '"break": 100',
    paths: [STRYKER],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*Bundle size\*\* is a ratchet recorded in `\.size-limit\.json`/,
    holds: "the ratchet a reviewer last accepted",
    pattern: '"limit"',
    paths: [RATCHET],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /The glob covers every emitted script rather than an entry point/,
    holds: "the glob the ratchet weighs",
    pattern: "dist/**/*.js",
    paths: [RATCHET],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /`apps\/web\/dist\/\*\*\/\*\.css` weighs what the/,
    holds: "the glob the stylesheet ratchet weighs",
    pattern: "dist/**/*.css",
    paths: [RATCHET],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /Each glob is pointed at `apps\/web\/dist` rather than at/,
    holds: "the glob the stylesheet ratchet weighs",
    pattern: "dist/**/*.css",
    paths: [RATCHET],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*The journey\*\* is measured on the built tree served by the deployment's own worker/,
    holds: "the script that holds the head's journey to the merge base's",
    pattern: "tools/journey/src/index.ts",
    paths: ["package.json"],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /its Slow 4G network profile, 150 ms of round-trip latency/,
    holds: "the round-trip latency the journey emulates",
    pattern: "latency: 150,",
    paths: [JOURNEY],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /the five options it does not switch on under `strict` are on in/,
    holds: "the strictest of those options, in the shared compiler settings",
    pattern: '"isolatedDeclarations": true',
    paths: ["tsconfig.base.json"],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /which is `minTokens` 100 and `minLines` 10 in `\.jscpd\.json`/,
    holds: "the duplication window the Sonar way defines",
    pattern: '"minTokens": 100',
    paths: [DUPLICATION],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /"Duplication in the new code is less than or equal to 3\.0%"/,
    holds: "the duplication threshold that gates the build",
    pattern: '"threshold": 3',
    paths: [DUPLICATION],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /by `osv-scanner --licenses` in the `dependencies` job/,
    holds: "the licence allowlist the dependencies job carries",
    pattern: "--licenses=",
    paths: [WORKFLOW],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*Imports may not form a cycle\*\*/,
    holds: "the import cycle rule that gates the build",
    pattern: "noImportCycles",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /sums each entry's duration in excess of 50 ms/,
    holds: "the long task threshold the journey sums against",
    pattern: "LONG_TASK_MS = 50",
    paths: [JOURNEY],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /The gesture is made ten times over now/,
    holds: "the number of gestures the room is measured over",
    pattern: "const GESTURES = 10",
    paths: [GESTURE],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /the three woff2 faces the page preloads, and the icons/,
    holds: "the glob the font ratchet weighs",
    pattern: "dist/fonts/*.woff2",
    paths: [RATCHET],
    files: 1,
  },
];
