const BIOME = "biome.json";
const PRODUCT = ["packages", ":!*.test.ts", ":!*.fixtures.ts"];
const RATCHET = ".size-limit.json";
const STRYKER = "stryker.config.json";
const CYCLOMATIC = ".oxlintrc.json";
const SOURCES = ["*.ts", "*.tsx"];
const CORPUS = "packages/core/src/corpus";

export const CLAIMS = [
  {
    adr: "0001-single-aggregating-source.md",
    says: /The one chain with a public catalogue API is the second implementation whenever it is built\./,
    holds: "modules that build a Source, tests aside",
    pattern: "): Source =>",
    paths: PRODUCT,
    files: 1,
  },
  {
    adr: "0004-booking-ends-at-a-deep-link.md",
    says: /A result carries the showtime without its ticketing URL/,
    holds: "the result view that drops the ticketing URL",
    pattern: 'Omit<Showtime, "ticketing">',
    paths: ["packages/client/src/ranking.ts"],
    files: 1,
  },
  {
    adr: "0001-single-aggregating-source.md",
    says: /Ship a single implementation of it: the aggregator\./,
    holds: "modules that build a Source, tests aside",
    pattern: "): Source =>",
    paths: PRODUCT,
    files: 1,
  },
  {
    adr: "0002-computation-on-the-client.md",
    says: /forwards the request upstream, and streams/,
    holds: "the header allowlist the proxy forwards",
    pattern: 'const FORWARDED = ["accept", "content-type", "user-agent"]',
    paths: ["apps/proxy/src/index.ts"],
    files: 1,
  },
  {
    adr: "0003-separate-view-layers-shared-core.md",
    says: /That constraint is enforced by dependency rules in the build, not by convention\./,
    holds: "the import ban the build declares over Core",
    pattern: "noRestrictedImports",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0003-separate-view-layers-shared-core.md",
    says: /`core` and `client` are shared without modification\./,
    holds: "files under apps naming Core's package directly",
    pattern: "@seatscout/core",
    paths: ["apps"],
    files: 0,
    witness: ["packages/client"],
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /by Biome's \[`noExcessiveCognitiveComplexity`\]/,
    holds: "the complexity rule that gates the build",
    pattern: "noExcessiveCognitiveComplexity",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /The line counter is \[cloc\]/,
    holds: "the toolchain naming the counter this decision picked",
    pattern: "cloc",
    paths: [
      "package.json",
      ".github",
      "tools",
      ":!*.test.ts",
      ":!*.fixtures.ts",
    ],
    files: 2,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*The number and its exception process\.\*\*/,
    holds: "the cyclomatic limit that gates the build",
    pattern: '"max": 10',
    paths: [CYCLOMATIC],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /the same documented meaning of `classic`/,
    holds: "the counting variant the limit is defined over",
    pattern: '"variant": "classic"',
    paths: [CYCLOMATIC],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*Lines per file\*\* may not exceed 300, by Biome's/,
    holds: "the file length rule that gates the build",
    pattern: "noExcessiveLinesPerFile",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /calls it greater than or equal to a break threshold of 100, and exits/,
    holds: "the mutation gate's breaking threshold",
    pattern: '"break": 100',
    paths: [STRYKER],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*Bundle size\*\* is a ratchet recorded in `\.size-limit\.json`/,
    holds: "the ratchet a reviewer last accepted",
    pattern: '"limit"',
    paths: [RATCHET],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /The glob covers every emitted script rather than an entry point/,
    holds: "the glob the ratchet weighs",
    pattern: "dist/**/*.js",
    paths: [RATCHET],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*The journey\*\* is measured on the built tree served by the deployment's own worker/,
    holds: "the script that holds the head's journey to the merge base's",
    pattern: "tools/journey/src/index.ts",
    paths: ["package.json"],
    files: 1,
  },
  {
    adr: "0007-prose-is-held-to-the-repository.md",
    says: /`pnpm counts` holds a count stated in prose to the structure that carries the items/,
    holds: "the command the counts gate runs under",
    pattern: "tools/counts-in-prose/src/index.ts",
    paths: ["package.json"],
    files: 1,
  },
  {
    adr: "0007-prose-is-held-to-the-repository.md",
    says: /`pnpm claims` holds a claim this repository's own documents make about it/,
    holds: "the command the claims gate runs under",
    pattern: "tools/claims-in-prose.mjs",
    paths: ["package.json"],
    files: 1,
  },
  {
    adr: "0008-guarantees-are-made-at-compile-time.md",
    says: /`noUnsafeTypeAssertion` refuses a type assertion in both spellings/,
    holds: "the rule that refuses a type assertion",
    pattern: "noUnsafeTypeAssertion",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0008-guarantees-are-made-at-compile-time.md",
    says: /`noTsIgnore` refuses the line-wide one/,
    holds: "the rule that refuses a line-wide suppression",
    pattern: "noTsIgnore",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0009-no-upstream-word-crosses-the-boundary.md",
    says: /so no module above it can name one even deliberately/,
    holds: "modules outside the adapter naming an upstream listing shape",
    pattern: "UpstreamShowtime",
    paths: ["packages", ":!packages/core/src/source", ":!*.test.ts"],
    files: 0,
    witness: ["packages/core/src/source"],
  },
  {
    adr: "0009-no-upstream-word-crosses-the-boundary.md",
    says: /\*\*Neither seat count is read, and neither can be\.\*\*/,
    holds: "TypeScript naming the upstream seat count anywhere",
    pattern: "totalSeatCount",
    paths: SOURCES,
    files: 0,
    witness: [CORPUS],
  },
  {
    adr: "0010-the-corpus-is-the-contract.md",
    says: /three that must not be read: `chainType`/,
    holds: "TypeScript naming the chain-specific seat label anywhere",
    pattern: "chainType",
    paths: SOURCES,
    files: 0,
    witness: [CORPUS],
  },
  {
    adr: "0010-the-corpus-is-the-contract.md",
    says: /The corpus is not part of Core's compiled product\./,
    holds: "the project that keeps the corpus out of what Core builds",
    pattern: "src/corpus",
    paths: ["packages/core/tsconfig.json"],
    files: 1,
  },
  {
    adr: "0011-a-nightly-reading-judges-the-world.md",
    says: /runs it nightly\. It is not a required check/,
    holds: "workflows that read the live Source",
    pattern: "test:live",
    paths: [".github"],
    files: 1,
  },
  {
    adr: "0012-every-mutant-must-die.md",
    says: /\*\*One thing is carved out: `apps\/native`\.\*\*/,
    holds: "the carve-out the mutation configuration declares",
    pattern: "!apps/native/src",
    paths: [STRYKER],
    files: 1,
  },
  {
    adr: "0013-only-the-catalogue-is-cached.md",
    says: /is the whole of the gate that keeps the writer the only writer/,
    holds: "the command the reach check runs under",
    pattern: "tools/no-cache-storage-reach/src/index.ts",
    paths: ["package.json"],
    files: 1,
  },
  {
    adr: "0013-only-the-catalogue-is-cached.md",
    says: /\*\*Every request the adapter makes asks for `no-store`\.\*\*/,
    holds: "modules naming the cache mode a read asks for",
    pattern: "no-store",
    paths: PRODUCT,
    files: 3,
  },
  {
    adr: "0014-the-room-is-read-from-its-drawing.md",
    says: /`gapBetween` is shared with `seat-group\.ts`/,
    holds: "modules reading the gap between two Seats",
    pattern: "gapBetween",
    paths: PRODUCT,
    files: 3,
  },
  {
    adr: "0015-a-result-is-one-seat-group-per-room.md",
    says: /which is the order `seatGroupsIn` already yields/,
    holds: "modules naming the function that cuts a run into Seat Groups",
    pattern: "seatGroupsIn",
    paths: PRODUCT,
    files: 3,
  },
  {
    adr: "0016-a-search-reports-its-coverage.md",
    says: /\*\*The fan-out is 24 workers over one queue\.\*\*/,
    holds: "the fan-out width the search runs at",
    pattern: "WIDTH = 24",
    paths: ["packages/client/src/search.ts"],
    files: 1,
  },
  {
    adr: "0017-retry-and-the-breaker-follow-published-policy.md",
    says: /\*\*The breaker is the three states of Nygard's/,
    holds: "modules naming the circuit breaker",
    pattern: "breaker",
    paths: PRODUCT,
    files: 2,
  },
  {
    adr: "0019-the-list-is-painted-once.md",
    says: /The query lives in the address as `movie`, `date`, `area` and `partySize`/,
    holds: "the module that reads a query out of the address",
    pattern: "partySize",
    paths: ["apps/web/src/terms.ts"],
    files: 1,
  },
];

export const UNCHECKED = {
  "0005-build-numbers-come-from-the-run-counter.md":
    "it is deprecated, and the resolver its pairs were held to has been deleted, so the " +
    "tree holds nothing for a search to reach; the pairs return with the release workflow",
  "0018-good-seats-are-scored-against-a-reference.md":
    "what a command can hold in it is the Seat Profile's own numbers, which " +
    "tools/counts-in-prose holds term by term, and everything else it cites is a " +
    "published standard or a measurement of rooms rather than a shape of this tree",
  "CONTEXT.md":
    "it is the domain glossary, and the sets and counts it states are held term by term " +
    "by tools/counts-in-prose, which is the right instrument for a count",
  "README.md":
    "it describes the product to a reader and states no shape of this tree that a search " +
    "could hold; what it says of the Reference profile is defined in CONTEXT.md, which is " +
    "where tools/counts-in-prose holds it",
};
