import { GATE_CLAIMS } from "./claims-in-prose.pairs.gates.mjs";

const BIOME = "biome.json";
const PRODUCT = ["packages", ":!*.test.ts", ":!*.fixtures.ts"];
const PROXY = "apps/proxy/src/index.ts";
const STRYKER = "stryker.config.json";
const SOURCES = ["*.ts", "*.tsx"];
const CORPUS = "packages/core/src/corpus";

export const CLAIMS = [
  {
    adr: "0001-single-aggregating-source.md",
    says: /The one chain with a public catalogue API is the second implementation whenever it is built\./,
    holds: "modules that build a Source, tests aside",
    pattern: "): Source =>",
    paths: PRODUCT,
    files: 1,
  },
  {
    adr: "0004-booking-ends-at-a-deep-link.md",
    says: /A result carries the showtime without its ticketing URL/,
    holds: "the result view that drops the ticketing URL",
    pattern: 'Omit<Showtime, "ticketing">',
    paths: ["packages/client/src/ranking.ts"],
    files: 1,
  },
  {
    adr: "0001-single-aggregating-source.md",
    says: /Ship a single implementation of it: the aggregator\./,
    holds: "modules that build a Source, tests aside",
    pattern: "): Source =>",
    paths: PRODUCT,
    files: 1,
  },
  {
    adr: "0002-computation-on-the-client.md",
    says: /forwards the request upstream, and streams/,
    holds: "the header allowlist the proxy forwards",
    pattern: 'const FORWARDED = ["accept", "content-type", "user-agent"]',
    paths: [PROXY],
    files: 1,
  },
  {
    adr: "0002-computation-on-the-client.md",
    says: /A request is carried only when its `Sec-Fetch-Site` reads `same-origin`\./,
    holds: "the fetch metadata the proxy reads",
    pattern: 'headers.get("sec-fetch-site")',
    paths: [PROXY],
    files: 1,
  },
  {
    adr: "0002-computation-on-the-client.md",
    says: /runs checks 170 candidates besides its listings\./,
    holds: "the corpus search the limit is sized from",
    pattern: "170 checked",
    paths: ["tests/e2e/query.spec.ts"],
    files: 1,
  },
  {
    adr: "0002-computation-on-the-client.md",
    says: /Three of the wider kind in a minute is 540, which is the limit\./,
    holds: "the rate limit the deployment declares",
    pattern: '"limit": 540',
    paths: ["apps/proxy/wrangler.json"],
    files: 1,
  },
  {
    adr: "0002-computation-on-the-client.md",
    says: /a request for any other path is answered 404 rather than forwarded/,
    holds: "the only path the proxy carries",
    pattern: 'const ROUTE = "/napi/"',
    paths: [PROXY],
    files: 1,
  },
  {
    adr: "0003-separate-view-layers-shared-core.md",
    says: /That constraint is enforced by dependency rules in the build, not by convention\./,
    holds: "the import ban the build declares over Core",
    pattern: "noRestrictedImports",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0003-separate-view-layers-shared-core.md",
    says: /\*\*All three packages and this application therefore set `lib` to `\["ES2022"\]`\*\*/,
    holds:
      "the projects that compile against the edition Hermes implements whole",
    pattern: '"lib": ["ES2022"]',
    paths: [
      "packages/core/tsconfig.json",
      "packages/client/tsconfig.json",
      "packages/view-logic/tsconfig.json",
      "apps/native/tsconfig.json",
      "apps/web/tsconfig.json",
      "tools/footprint/tsconfig.json",
    ],
    files: 4,
  },
  {
    adr: "0003-separate-view-layers-shared-core.md",
    says: /`core` and `client` are shared without modification\./,
    holds: "files under apps naming Core's package directly",
    pattern: "@seatscout/core",
    paths: ["apps"],
    files: 0,
    witness: ["packages/client"],
  },
  {
    adr: "0007-prose-is-held-to-the-repository.md",
    says: /`pnpm counts` holds a count stated in prose to the structure that carries the items/,
    holds: "the command the counts gate runs under",
    pattern: "tools/counts-in-prose/src/index.ts",
    paths: ["package.json"],
    files: 1,
  },
  {
    adr: "0007-prose-is-held-to-the-repository.md",
    says: /`pnpm claims` holds a claim this repository's own documents make about it/,
    holds: "the command the claims gate runs under",
    pattern: "tools/claims-in-prose.mjs",
    paths: ["package.json"],
    files: 1,
  },
  {
    adr: "0008-guarantees-are-made-at-compile-time.md",
    says: /`noUnsafeTypeAssertion` refuses a type assertion in both spellings/,
    holds: "the rule that refuses a type assertion",
    pattern: "noUnsafeTypeAssertion",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0008-guarantees-are-made-at-compile-time.md",
    says: /`noTsIgnore` refuses the line-wide one/,
    holds: "the rule that refuses a line-wide suppression",
    pattern: "noTsIgnore",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0009-no-upstream-word-crosses-the-boundary.md",
    says: /so no module above it can name one even deliberately/,
    holds: "modules outside the adapter naming an upstream listing shape",
    pattern: "UpstreamShowtime",
    paths: ["packages", ":!packages/core/src/source", ":!*.test.ts"],
    files: 0,
    witness: ["packages/core/src/source"],
  },
  {
    adr: "0009-no-upstream-word-crosses-the-boundary.md",
    says: /\*\*Neither seat count is read, and neither can be\.\*\*/,
    holds: "TypeScript naming the upstream seat count anywhere",
    pattern: "totalSeatCount",
    paths: SOURCES,
    files: 0,
    witness: [CORPUS],
  },
  {
    adr: "0010-the-corpus-is-the-contract.md",
    says: /three that must not be read: `chainType`/,
    holds: "TypeScript naming the chain-specific seat label anywhere",
    pattern: "chainType",
    paths: SOURCES,
    files: 0,
    witness: [CORPUS],
  },
  {
    adr: "0010-the-corpus-is-the-contract.md",
    says: /The corpus is not part of Core's compiled product\./,
    holds: "the project that keeps the corpus out of what Core builds",
    pattern: "src/corpus",
    paths: ["packages/core/tsconfig.json"],
    files: 1,
  },
  {
    adr: "0011-a-nightly-reading-judges-the-world.md",
    says: /runs it nightly\. It is not a required check/,
    holds: "workflows that read the live Source",
    pattern: "test:live",
    paths: [".github"],
    files: 1,
  },
  {
    adr: "0012-every-mutant-must-die.md",
    says: /\*\*One thing is carved out: the `\.tsx` files under `apps\/native\/src`\.\*\*/,
    holds: "the carve-out the mutation configuration declares",
    pattern: "!apps/native/src",
    paths: [STRYKER],
    files: 1,
  },
  {
    adr: "0013-only-the-catalogue-is-cached.md",
    says: /are the whole of the gate that keeps the writer the only writer/,
    holds: "the property rule that keeps the writer the only writer",
    pattern: "noJsRestrictedProperties",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0013-only-the-catalogue-is-cached.md",
    says: /the override that carries it excludes one file/,
    holds: "the one file the global ban excludes",
    pattern: '"!apps/web/src/worker/cache.ts"',
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0013-only-the-catalogue-is-cached.md",
    says: /which this decision raises from its recommended warning to an error/,
    holds: "the escape rule raised to an error",
    pattern: '"noUselessEscapeInString": "error"',
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0013-only-the-catalogue-is-cached.md",
    says: /\*\*Every request the adapter makes asks for `no-store`\.\*\*/,
    holds: "modules naming the cache mode a read asks for",
    pattern: "no-store",
    paths: PRODUCT,
    files: 3,
  },
  {
    adr: "0014-the-room-is-read-from-its-drawing.md",
    says: /`gapBetween` is shared with `seat-group\.ts`/,
    holds: "modules reading the gap between two Seats",
    pattern: "gapBetween",
    paths: PRODUCT,
    files: 3,
  },
  {
    adr: "0015-a-result-is-one-seat-group-per-room.md",
    says: /which is the order `seatGroupsIn` already yields/,
    holds: "modules naming the function that cuts a run into Seat Groups",
    pattern: "seatGroupsIn",
    paths: PRODUCT,
    files: 3,
  },
  {
    adr: "0016-a-search-reports-its-coverage.md",
    says: /\*\*The fan-out is 24 workers over one queue\.\*\*/,
    holds: "the fan-out width the search runs at",
    pattern: "WIDTH = 24",
    paths: ["packages/client/src/fan-out.ts"],
    files: 1,
  },
  {
    adr: "0017-retry-and-the-breaker-follow-published-policy.md",
    says: /\*\*The breaker is the three states of Nygard's/,
    holds: "modules naming the circuit breaker",
    pattern: "breaker",
    paths: PRODUCT,
    files: 2,
  },
  {
    adr: "0019-the-list-is-painted-once.md",
    says: /The query lives in the address as `movie`, `date`, `area`, `partySize`, `chain`/,
    holds: "the module that reads a query out of the address",
    pattern: "partySize",
    paths: ["packages/view-logic/src/terms.ts"],
    files: 1,
  },
  {
    adr: "README.md",
    says: /Both addresses name the SDK, so both of them move when `apps\/native` moves to a new Expo SDK/,
    holds: "the manifest holding the Expo SDK the phone's addresses name",
    pattern: '"expo": "57.',
    paths: ["apps/native/package.json"],
    files: 1,
  },
  ...GATE_CLAIMS,
];
