import { BUNDLE_CLAIMS } from "./claims-in-prose.pairs.bundle.mjs";
import { DEVICE_CLAIMS } from "./claims-in-prose.pairs.device.mjs";
import { GATE_CLAIMS } from "./claims-in-prose.pairs.gates.mjs";
import { MUTATION_CLAIMS } from "./claims-in-prose.pairs.mutation.mjs";
import { PROSE_CLAIMS } from "./claims-in-prose.pairs.prose.mjs";
import { SEARCH_CLAIMS } from "./claims-in-prose.pairs.search.mjs";

const BIOME = "biome.json";
const PRODUCT = ["packages", ":!*.test.ts", ":!*.fixtures.ts"];
const SOURCES = ["*.ts", "*.tsx"];
const CORPUS = "packages/core/src/corpus";

export const CLAIMS = [
  {
    adr: "0001-single-aggregating-source.md",
    says: /The one chain with a public catalogue API is the second implementation whenever it is built\./,
    holds: "modules that build a Source, tests aside",
    pattern: "): Source =>",
    paths: PRODUCT,
    files: 1,
  },
  {
    adr: "0004-booking-ends-at-a-deep-link.md",
    says: /A result carries the showtime without its ticketing URL/,
    holds: "the result view that drops the ticketing URL",
    pattern: 'Omit<Showtime, "ticketing">',
    paths: ["packages/client/src/ranking.ts"],
    files: 1,
  },
  {
    adr: "0004-booking-ends-at-a-deep-link.md",
    says: /Showtime's ticketing URL in the in-app browser exactly as the Source gave it/,
    holds: "the checkout that opens the carried URL in the in-app browser",
    pattern: 'import { openBrowserAsync } from "expo-web-browser"',
    paths: ["apps/native/src/host"],
    files: 1,
  },
  {
    adr: "0003-separate-view-layers-shared-core.md",
    says: /`tools\/lint\/no-platform-reads\.grit`\s+refuses `Platform\.OS` and `Platform\.select`/,
    holds:
      "the rule that keeps platform reads in the design system and the host",
    pattern: "no-platform-reads.grit",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0001-single-aggregating-source.md",
    says: /Ship a single implementation of it: the aggregator\./,
    holds: "modules that build a Source, tests aside",
    pattern: "): Source =>",
    paths: PRODUCT,
    files: 1,
  },
  {
    adr: "0002-computation-on-the-client.md",
    says: /so every read names the\s+upstream as its referer\./,
    holds: "the referer every read from the device carries",
    pattern: "Referer:",
    paths: ["apps/native/src/host", ":!*.test.ts"],
    files: 1,
  },
  {
    adr: "0003-separate-view-layers-shared-core.md",
    says: /That constraint is enforced by dependency rules in the build, not by convention\./,
    holds: "the import ban the build declares over Core",
    pattern: "noRestrictedImports",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0003-separate-view-layers-shared-core.md",
    says: /\*\*All three packages and this application therefore set `lib` to `\["ES2022"\]`\*\*/,
    holds:
      "the projects that compile against the edition Hermes implements whole",
    pattern: '"lib": ["ES2022"]',
    paths: [
      "packages/core/tsconfig.json",
      "packages/client/tsconfig.json",
      "packages/view-logic/tsconfig.json",
      "apps/native/tsconfig.json",
      "tools/footprint/tsconfig.json",
    ],
    files: 4,
  },
  {
    adr: "0003-separate-view-layers-shared-core.md",
    says: /`core` and `client` are shared without modification\./,
    holds: "files under apps naming Core's package directly",
    pattern: "@seatscout/core",
    paths: ["apps"],
    files: 0,
    witness: ["packages/client"],
  },
  {
    adr: "0007-prose-is-held-to-the-repository.md",
    says: /`pnpm counts` holds a count stated in prose to the structure that carries the items/,
    holds: "the command the counts gate runs under",
    pattern: "tools/counts-in-prose/src/index.ts",
    paths: ["package.json"],
    files: 1,
  },
  {
    adr: "0007-prose-is-held-to-the-repository.md",
    says: /`pnpm claims` holds a claim this repository's own documents make about it/,
    holds: "the command the claims gate runs under",
    pattern: "tools/claims-in-prose.mjs",
    paths: ["package.json"],
    files: 1,
  },
  {
    adr: "0008-guarantees-are-made-at-compile-time.md",
    says: /`noUnsafeTypeAssertion` refuses a type assertion in both spellings/,
    holds: "the rule that refuses a type assertion",
    pattern: "noUnsafeTypeAssertion",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0008-guarantees-are-made-at-compile-time.md",
    says: /`noTsIgnore` refuses the line-wide one/,
    holds: "the rule that refuses a line-wide suppression",
    pattern: "noTsIgnore",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0009-no-upstream-word-crosses-the-boundary.md",
    says: /so no module above it can name one even deliberately/,
    holds: "modules outside the adapter naming an upstream listing shape",
    pattern: "UpstreamShowtime",
    paths: ["packages", ":!packages/core/src/source", ":!*.test.ts"],
    files: 0,
    witness: ["packages/core/src/source"],
  },
  {
    adr: "0009-no-upstream-word-crosses-the-boundary.md",
    says: /\*\*Neither seat count is read, and neither can be\.\*\*/,
    holds: "TypeScript naming the upstream seat count anywhere",
    pattern: "totalSeatCount",
    paths: SOURCES,
    files: 0,
    witness: [CORPUS],
  },
  {
    adr: "0010-the-corpus-is-the-contract.md",
    says: /three that must not be read: `chainType`/,
    holds: "TypeScript naming the chain-specific seat label anywhere",
    pattern: "chainType",
    paths: SOURCES,
    files: 0,
    witness: [CORPUS],
  },
  {
    adr: "0010-the-corpus-is-the-contract.md",
    says: /The corpus is not part of Core's compiled product\./,
    holds: "the project that keeps the corpus out of what Core builds",
    pattern: "src/corpus",
    paths: ["packages/core/tsconfig.json"],
    files: 1,
  },
  {
    adr: "0011-a-nightly-reading-judges-the-world.md",
    says: /runs it nightly\. It is not a required check/,
    holds: "workflows that read the live Source",
    pattern: "test:live",
    paths: [".github"],
    files: 1,
  },
  {
    adr: "0013-only-the-catalogue-is-cached.md",
    says: /\*\*Every request the adapter makes asks for `no-store`\.\*\*/,
    holds: "modules naming the cache mode a read asks for",
    pattern: "no-store",
    paths: PRODUCT,
    files: 3,
  },
  {
    adr: "0014-the-room-is-read-from-its-drawing.md",
    says: /`gapBetween` is shared with `seat-group\.ts`/,
    holds: "modules reading the gap between two Seats",
    pattern: "gapBetween",
    paths: PRODUCT,
    files: 3,
  },
  {
    adr: "0015-a-result-is-one-seat-group-per-room.md",
    says: /which is the order `seatGroupsIn` already yields/,
    holds: "modules naming the function that cuts a run into Seat Groups",
    pattern: "seatGroupsIn",
    paths: PRODUCT,
    files: 3,
  },
  {
    adr: "README.md",
    says: /set by `"runtimeVersion": \{ "policy": "fingerprint" \}` in\s+`apps\/native\/app\.json`/,
    holds: "the app config holding the fingerprint runtime version policy",
    pattern: '"policy": "fingerprint"',
    paths: ["apps/native/app.json"],
    files: 1,
  },
  {
    adr: "0021-a-merge-publishes-a-preview-not-a-release.md",
    says: /publishes an EAS Update to the `preview` channel, and nothing more/,
    holds: "the channel a merge publishes to",
    pattern: "CHANNEL: preview",
    paths: [".github/workflows/preview.yml"],
    files: 1,
  },
  {
    adr: "0021-a-merge-publishes-a-preview-not-a-release.md",
    says: /`eas-cli` runs through `npx` at a version the workflow pins/,
    holds: "the pinned publisher the workflow runs through npx",
    pattern: 'npx --yes "$EAS_CLI"',
    paths: [".github/workflows/preview.yml"],
    files: 1,
  },
  ...GATE_CLAIMS,
  ...DEVICE_CLAIMS,
  ...MUTATION_CLAIMS,
  ...SEARCH_CLAIMS,
  ...PROSE_CLAIMS,
  ...BUNDLE_CLAIMS,
];
