const BIOME = "biome.json";
const RATCHET = ".size-limit.json";
const STRYKER = "stryker.config.mjs";
const CYCLOMATIC = ".oxlintrc.json";
const DUPLICATION = ".jscpd.json";
const WORKFLOW = ".github/workflows/ci.yml";
const COLOURS = "tools/lint/no-colour-literals.grit";
const BASELINE = ".github/workflows/baseline.yml";

export const GATE_CLAIMS = [
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /by Biome's \[`noExcessiveCognitiveComplexity`\]/,
    holds: "the complexity rule that gates the build",
    pattern: "noExcessiveCognitiveComplexity",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /The line counter is \[cloc\]/,
    holds: "the toolchain naming the counter this decision picked",
    pattern: "cloc",
    paths: [
      "package.json",
      ".github",
      "tools",
      ":!*.test.ts",
      ":!*.fixtures.ts",
    ],
    files: 2,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /the same documented meaning of `classic`/,
    holds: "the counting variant the limit is defined over",
    pattern: '"variant": "classic"',
    paths: [CYCLOMATIC],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*Lines per file\*\* may not exceed 300, by Biome's/,
    holds: "the file length rule that gates the build",
    pattern: "noExcessiveLinesPerFile",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /calls it greater than or equal to a break threshold of 100, and exits/,
    holds: "the mutation gate's breaking threshold",
    pattern: "break: 100",
    paths: [STRYKER],
    files: 1,
  },
  {
    adr: "0012-every-mutant-must-die.md",
    says: /includes that workspace's test files and no others/,
    holds:
      "the configuration that limits a shard to the tests its workspace holds",
    pattern: "configFor(shard?.workspace)",
    paths: ["vitest.stryker.config.ts"],
    files: 1,
  },
  {
    adr: "0012-every-mutant-must-die.md",
    says: /The Vitest runner's `vitest\.related` is turned off for the/,
    holds: "the setting that keeps related mode off a shard's static mutants",
    pattern: "related: false",
    paths: [STRYKER],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*Bundle size\*\* is a ratchet recorded in `\.size-limit\.json`/,
    holds: "the ratchet a reviewer last accepted",
    pattern: '"limit"',
    paths: [RATCHET],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /The glob covers every emitted script rather than an entry point/,
    holds: "the glob the ratchet weighs",
    pattern: "dist/_expo/static/js/",
    paths: [RATCHET],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /the five options it does not switch on under `strict` are on in/,
    holds: "the strictest of those options, in the shared compiler settings",
    pattern: '"isolatedDeclarations": true',
    paths: ["tsconfig.base.json"],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /which is `minTokens` 100 and `minLines` 10 in `\.jscpd\.json`/,
    holds: "the duplication window the Sonar way defines",
    pattern: '"minTokens": 100',
    paths: [DUPLICATION],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /"Duplication in the new code is less than or equal to 3\.0%"/,
    holds: "the duplication threshold that gates the build",
    pattern: '"threshold": 3',
    paths: [DUPLICATION],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /by `osv-scanner --licenses` in the `dependencies` job/,
    holds: "the licence allowlist the dependencies job carries",
    pattern: "--licenses=",
    paths: [WORKFLOW],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*React's two hook rules are named rather than left to detection\.\*\*/,
    holds: "the dependency rule that gates every hook",
    pattern: '"useExhaustiveDependencies": "error"',
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /`react-hooks\/rules-of-hooks`\. Each rule page records the rule as recommended/,
    holds: "the rule that gates where a hook is called",
    pattern: '"useHookAtTopLevel": "error"',
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*An import of a package the nearest manifest does not declare is refused\*\*/,
    holds: "the undeclared import rule that gates the build",
    pattern: '"noUndeclaredDependencies": "error"',
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*One version of every shared dependency, across every manifest and the override file\*\*/,
    holds: "the command that holds them to one version",
    pattern: "syncpack lint",
    paths: ["package.json"],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /Expo publishes that table and `expo install --check` reads it/,
    holds: "the two Expo checks the quality job runs",
    pattern: "@seatscout/native run",
    paths: [WORKFLOW],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /gates on a significant regression only below 5 per cent/,
    holds: "the reading below which the render gate may gate",
    pattern: "reading < 5",
    paths: [WORKFLOW],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /one of the CSS Color Module Level 4 named colours/,
    holds: "the named colours the screen rule refuses",
    pattern: "rebeccapurple",
    paths: [COLOURS],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*What the emulator reads is measured on main, held to the run before/,
    holds: "the Flashlight reading of the walk",
    pattern: "flashlight test",
    paths: [".github", "apps/native/e2e"],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /it runs on main as a trend with an alarm/,
    holds: "a pull request that runs the reading",
    pattern: "e2e/measure.sh",
    paths: [WORKFLOW],
    files: 0,
    witness: [BASELINE],
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /files an issue labelled `device-red`/,
    holds: "the alarm the reading on main files",
    pattern: "gh issue create --label device-red",
    paths: [BASELINE],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /A push never\s+cancels a reading in progress/,
    holds: "the Baseline concurrency that lets a reading finish",
    pattern: "cancel-in-progress: false",
    paths: [BASELINE],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /The judge rounds this commit's median and the previous run's worst to those same places/,
    holds: "the precision each measure is compared at",
    pattern: "roundedTo(value, axis.decimals)",
    paths: ["tools/device/src"],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /run Baseline on main from the Actions tab with `accept` set to the reason/,
    holds: "the input that keeps a reading by hand",
    pattern: "inputs.accept",
    paths: [BASELINE],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /`android` job reads them with `cache-read-only`/,
    holds: "the pull request's read-only Gradle caches",
    pattern: "cache-read-only: true",
    paths: [WORKFLOW],
    files: 1,
  },
];
