const BIOME = "biome.json";
const BUNDLES = ".size-limit.json";
const STRYKER = "stryker.config.mjs";
const CYCLOMATIC = ".oxlintrc.json";
const DUPLICATION = ".jscpd.json";
const WORKFLOW = ".github/workflows/ci.yml";
const COLOURS = "tools/lint/no-colour-literals.grit";
const WORKSPACE = "pnpm-workspace.yaml";

export const GATE_CLAIMS = [
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /by Biome's \[`noExcessiveCognitiveComplexity`\]/,
    holds: "the complexity rule that gates the build",
    pattern: "noExcessiveCognitiveComplexity",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /The line counter is \[cloc\]/,
    holds: "the toolchain naming the counter this decision picked",
    pattern: "cloc",
    paths: [
      "package.json",
      ".github",
      "tools",
      ":!*.test.ts",
      ":!*.fixtures.ts",
    ],
    files: 2,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /the same documented meaning of `classic`/,
    holds: "the counting variant the limit is defined over",
    pattern: '"variant": "classic"',
    paths: [CYCLOMATIC],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*Lines per file\*\* may not exceed 300, by Biome's/,
    holds: "the file length rule that gates the build",
    pattern: "noExcessiveLinesPerFile",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /calls it greater than or equal to a break threshold of 100, and exits/,
    holds: "the mutation gate's breaking threshold",
    pattern: "break: 100",
    paths: [STRYKER],
    files: 1,
  },
  {
    adr: "0012-every-mutant-must-die.md",
    says: /The change is read against the merge commit's first parent/,
    holds: "the plan read against the merge commit's first parent",
    pattern: "--plan HEAD^1",
    paths: [WORKFLOW],
    files: 1,
  },
  {
    adr: "0012-every-mutant-must-die.md",
    says: /includes that workspace's test files and no others/,
    holds:
      "the configuration that limits a shard to the tests its workspace holds",
    pattern: "configFor(shard?.workspace)",
    paths: ["vitest.stryker.config.ts"],
    files: 1,
  },
  {
    adr: "0012-every-mutant-must-die.md",
    says: /So a Jest shard runs two at a time\./,
    holds: "the two Jest runners a shard runs at once",
    pattern: "JEST_RUNNERS_AT_ONCE = 2",
    paths: [STRYKER],
    files: 1,
  },
  {
    adr: "0012-every-mutant-must-die.md",
    says: /`stryker\.config\.mjs` multiplies the 1\.5 by the number of projects/,
    holds: "the timeout factor a Jest shard scales by its projects",
    pattern:
      "STRYKER_DEFAULT_TIMEOUT_FACTOR * (await projectCountIn(shard.jest))",
    paths: [STRYKER],
    files: 1,
  },
  {
    adr: "0012-every-mutant-must-die.md",
    says: /The Vitest runner's `vitest\.related` is turned off for the/,
    holds: "the setting that keeps related mode off a shard's static mutants",
    pattern: "related: false",
    paths: [STRYKER],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*Bundle size is held to main, weighed in the same job\.\*\*/,
    holds: "the main side the measure job exports",
    pattern: '--main-tree "$RUNNER_TEMP/main"',
    paths: [WORKFLOW],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /unless\s+the pull request carries the `bundle-grows` label/,
    holds: "the label that accepts a bigger bundle",
    pattern: "grep -qx bundle-grows",
    paths: [WORKFLOW],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /The glob covers every emitted script rather than an entry point/,
    holds: "the glob each bundle is weighed by",
    pattern: "dist/_expo/static/js/",
    paths: [BUNDLES],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /the five options it does not switch on under `strict` are on in/,
    holds: "the strictest of those options, in the shared compiler settings",
    pattern: '"isolatedDeclarations": true',
    paths: ["tsconfig.base.json"],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /which is `minTokens` 100 and `minLines` 10 in `\.jscpd\.json`/,
    holds: "the duplication window the Sonar way defines",
    pattern: '"minTokens": 100',
    paths: [DUPLICATION],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /"Duplication in the new code is less than or equal to 3\.0%"/,
    holds: "the duplication threshold that gates the build",
    pattern: '"threshold": 3',
    paths: [DUPLICATION],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /by `osv-scanner --licenses` in the `dependencies` job/,
    holds: "the licence allowlist the dependencies job carries",
    pattern: "--licenses=",
    paths: [WORKFLOW],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*React's two hook rules are named rather than left to detection\.\*\*/,
    holds: "the dependency rule that gates every hook",
    pattern: '"useExhaustiveDependencies": "error"',
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /`react-hooks\/rules-of-hooks`\. Each rule page records the rule as recommended/,
    holds: "the rule that gates where a hook is called",
    pattern: '"useHookAtTopLevel": "error"',
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*An import of a package the nearest manifest does not declare is refused\*\*/,
    holds: "the undeclared import rule that gates the build",
    pattern: '"noUndeclaredDependencies": "error"',
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /\*\*One version of every shared dependency, across every manifest and the override file\*\*/,
    holds: "the command that holds them to one version",
    pattern: "syncpack lint",
    paths: ["package.json"],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /Expo publishes that table and `expo install --check` reads it/,
    holds: "the two Expo checks the quality job runs",
    pattern: "@seatscout/native run",
    paths: [WORKFLOW],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /one of the CSS Color Module Level 4 named colours/,
    holds: "the named colours the screen rule refuses",
    pattern: "rebeccapurple",
    paths: [COLOURS],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /The cheap first layer is a Grit plugin, `tools\/lint\/no-literal-ids\.grit`/,
    holds: "the rule that refuses a literal id",
    pattern: "no-literal-ids.grit",
    paths: [BIOME],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /also lists each id that two elements carry, and any such id fails the/,
    holds: "the scan's own check for a shared id",
    pattern: 'querySelectorAll("[id]")',
    paths: ["tests/app/app.fixtures.ts"],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /`apps\/native\/test\/setup\.tsx` runs `test\/audit\.ts` over\s+everything the test rendered/,
    holds: "the audit every screen test ends with",
    pattern: "await audit(house);",
    paths: ["apps/native/test/setup.tsx"],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /3 to 1 at 24 or at 18\.66 in\s+bold/,
    holds: "the size bold words count as large at",
    pattern: "const LARGE_BOLD = 18.66;",
    paths: ["apps/native/test/audit.ts"],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /44 pt on iOS and 48 dp on Android/,
    holds: "the touch floor of each platform",
    pattern: 'os === "ios" ? 44 : 48',
    paths: ["apps/native/src/design-system/touch.ts"],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /`uuid` is held at\s+11\.1\.1/,
    holds: "the uuid release the Xcode project parser can require",
    pattern: "uuid: 11.1.1",
    paths: [WORKSPACE],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /`exit` is aliased to `exit-x`/,
    holds: "the maintained fork standing in for exit",
    pattern: "exit: npm:exit-x@",
    paths: [WORKSPACE],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /`@types\/jsdom` is held at 30\.0\.0/,
    holds: "the jsdom types that type-check",
    pattern: "'@types/jsdom': 30.0.0",
    paths: [WORKSPACE],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /significant and at or above 6\.3 per cent/,
    holds: "the slowdown below which the render gate reads drift",
    pattern: 'SLOWDOWN_FLOOR: "0.063"',
    paths: [WORKFLOW],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /So the job runs each scenario 20 times/,
    holds: "the runs each render scenario takes",
    pattern: "configure({ runs: 20 });",
    paths: ["apps/native/test/reassure.cjs"],
    files: 1,
  },
  {
    adr: "0006-gates-cite-a-standard-or-measure-a-regression.md",
    says: /and its blanked copy, which a test holds\s+byte for byte/,
    holds: "the test that holds the blanked copy of the planted script",
    pattern: "strings-holding-comment-markers.blanked.ts.txt",
    paths: ["tools/footprint/src"],
    files: 1,
  },
];
